default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kanicompanion_development
  url: <%= ENV.fetch("DATABASE_URL", "postgres://kani:kani_dev@localhost:5432/kanicompanion_development") %>

test:
  <<: *default
  database: kanicompanion_test
  username: kani
  password: kani_dev
  host: localhost

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>